### ISSUE TITLE
User policy

### ISSUE THREAD

**Issue by sypher007** [lithnet/idle-logoff#14]
I've got an issue with the GPO settings.

When I set the GPO using Computer configuration -> Administrative templates -> Lithnet it works without a problem for all users. When I set the GPO using User configuration -> Administrative templates -> Lithnet to be able to specify certain users the policy is applied but the logoff doesn't work.

**Comment by ryannewington** [comment]
Is the GPO applied to a container containing the users or computers ?

**Comment by jmartins1** [comment]
I believe this is a computer GPO. Meaning you have to assign it to a computer OU. Assigning it to a user OU will cause it to fail.

**Comment by zaphod777** [comment]
Is it possible to have this target only certain users on a particular PC using a GPO? From the looks of it this will only target all users of a particular PC.

**Comment by jmartins1** [comment]
You can add the launch command to the user's login script.

⁣Sent from BlueMail ​

**Comment by ryannewington** [comment]
To do that, you'd need to configure it as a user policy, but that policy will apply to any computer the user logs into that has idle logoff installed. 

Otherwise you'd have to do something creative like what @jmartins1 suggested. Stopping idlelogoff from autostarting on its own, and selectively launching it on a per user basis
