### ISSUE TITLE
unexpected reboot

### ISSUE THREAD

**Issue by albetorivas** [lithnet/idle-logoff#4]
Hello, 
Today we had one user (user 2) who was actively using a computer "X" when suddenly it was rebooted by lithnet application because (user 1) reached the idle time.

( user 1 ) : Left the office with the computer "X" locked.
( user 2 ) : Arrived to the office and logged on computer "X"

Issue: Lithnet application is considering idle time for a disconnected session ( State Disc ), would be possible to avoid reboot because of idle time reached on disc session?

thanks
alberto.rivas@outlook.com

**Comment by ryannewington** [comment]
@albetorivas I can see how this is a problem, but it is a tricky one to address. The problem is that the agent runs in every user's session independently, and doesn't know about any other user sessions. The original design only ever provided support for logging a user off, so this was never a problem, because only the idle session was logged off. 

In this scenario, there are two different processes with their own timers running that do not know about each other. The only workaround I can think of at this time is to not use the reboot functionality.

I'll leave this issue open, but I'll need a bit more time to think through a solution for this issue.

**Comment by albetorivas** [comment]
Thank you!

**Comment by ryannewington** [comment]
@albetorivas try this test build

I've made it logoff instead of reboot if other instances of lithnet.idlelogoff are detected. So only the last client logged in should trigger a reboot when they idle.

[lithnet.idlelogoff.setup.msi.zip](https://github.com/lithnet/idle-logoff/files/1448622/lithnet.idlelogoff.setup.msi.zip)

**Comment by ryannewington** [comment]
Updated build. Let me know if you are happy with this and i'll make it live 
[lithnet.idlelogoff.setup.msi.zip](https://github.com/lithnet/idle-logoff/files/1452090/lithnet.idlelogoff.setup.msi.zip)

**Comment by albetorivas** [comment]
Hello,
I will test it, I'll let you know ! .. thanks for the effort...

Best Regards
Alberto Rivas

Sent from my iPhone

On Nov 7, 2017, at 18:55, Ryan Newington <notifications@github.com<mailto:notifications@github.com>> wrote:


Updated build. Let me know if you are happy with this and i'll make it live
lithnet.idlelogoff.setup.msi.zip<https://github.com/lithnet/idle-logoff/files/1452090/lithnet.idlelogoff.setup.msi.zip>

**Comment by ryannewington** [comment]
Hi @albetorivas,

Did you get a chance to test this?

**Comment by albetorivas** [comment]
Hello Ryan,

I haven't test it yet.  I will before the end of this week

by Friday I will email you


thanks !

Alberto


________________________________
De: Ryan Newington <notifications@github.com>
Enviado: domingo, 3 de diciembre de 2017 06:02 p. m.
Para: lithnet/idle-logoff
CC: albetorivas; Mention
Asunto: Re: [lithnet/idle-logoff] unexpected reboot (#4)


Hi @albetorivas<https://github.com/albetorivas>,

Did you get a chance to test this?

**Comment by albetorivas** [comment]
Hello Ryan,

I have tested it, and I can confirm you it works just great. Second user with Disc State was the only one kicked out


Thank you!


Regards

alberto.rivas@outlook.com






________________________________
De: Ryan Newington <notifications@github.com>
Enviado: domingo, 3 de diciembre de 2017 06:02 p. m.
Para: lithnet/idle-logoff
CC: albetorivas; Mention
Asunto: Re: [lithnet/idle-logoff] unexpected reboot (#4)


Hi @albetorivas<https://github.com/albetorivas>,

Did you get a chance to test this?

**Comment by ryannewington** [comment]
Thanks @albetorivas.

Released https://github.com/lithnet/idle-logoff/releases/tag/v1.1.6521
